### ISSUE TITLE
【SP/フッター】スクロールするとフッターが浮く

### ISSUE THREAD

**Issue by NKeisuke** [NKeisuke/ampersands-new-site#17]
- [ ] safariでスクロールしてデフォルトのフッターが消えた時に、サイトのフッターが一瞬止まって浮いてしまいますので、スクロールに合わせて動くようにして下さい。

![016](https://cloud.githubusercontent.com/assets/17138141/17283165/5e56592e-57e8-11e6-9125-89b8e2336312.jpg)

**Comment by umatobishima** [comment]
@tetsuya0987 
https://f-tra.jp/blog/smartphone/4580

**Comment by NKeisuke** [comment]
https://webkikaku.co.jp/blog/webdesign/googlemap-customize/
