### ISSUE TITLE
【PC/ABOUT ページ】

### ISSUE THREAD

**Issue by umatobishima** [NKeisuke/ampersands-new-site#18]
@tetsuya0987 
- [x] 1.背景をネイビーにしてください。
- [x] 2.他と合わせて文字を大きくしてください。（inVisionを参照してください。）
- [x] 3.文字を大きくしてください。（inVisionを参照してください。）
- [x] 4.ヘッダーと頭を揃えてください。
- [x] 5.文字を大きくしてください。（inVisionを参照してください。）
- [x] 6.文字を游ゴシック　ボールドにしてください。
- [x] 7.文字を大きくしてください。
  字間もあけてください。
  （inVisionを参照してください。）
- [x] 8.ヘッダーと頭を揃えてください。

![11](https://cloud.githubusercontent.com/assets/17138127/17283089/907055be-57e7-11e6-8cf2-8b6f55b7134a.jpg)
- [x] 9.距離を開けてください。
- [x] 10.文字を大きくしてください。（inVisionを参照してください。）
- [x] 11.文字を大きくしてください。（inVisionを参照してください。）
- [x] 12.本文の幅を写真の横幅に揃えてください。（inVisionを参照してください。）

![12](https://cloud.githubusercontent.com/assets/17138127/17283243/36a0f0dc-57e9-11e6-99d0-7ae4706d31ec.jpg)

**Comment by umatobishima** [comment]
@tetsuya0987 
- [x] 1. スペースが空いているので詰めてください。
- [x] 2. 頭が揃ってないので揃えてください。
  その分、説明文の改行が増えても大丈夫です。

![1](https://cloud.githubusercontent.com/assets/17138127/17724182/cceada4c-647a-11e6-9b20-0012a1ca2507.jpg)

**Comment by NKeisuke** [comment]
@tetsuya0987 1.の修正だけれど、スクロールしてグローバルナビが隠れた後、ABOUT USのローカルナビが上につくように詰めて下さい。
↓Mac Book Proの部分のナビのように
http://www.apple.com/jp/macbook-pro
