### ISSUE TITLE
【PC/ABOUT ページ　固定ローカルナビ】

### ISSUE THREAD

**Issue by umatobishima** [NKeisuke/ampersands-new-site#20]
@tetsuya0987 
- [x] 1.スクロールの際、固定してください。
  その際、上のスペースは詰めてください。

![13](https://cloud.githubusercontent.com/assets/17138127/17284367/02af389a-57f5-11e6-8dc9-c0fd9e9ef5a4.jpg)

**Comment by umatobishima** [comment]
@tetsuya0987 
上のスペースは詰めてください！

**Comment by NKeisuke** [comment]
アートディレクターの飛嶋由馬、中村圭佑が2012年に設立したデザインチーム。媒体や形式にこだわらず、デザインを通じたコミュニケーションで、常に人とプロジェクトとの良質な関係を築けるように考えている。
