### ISSUE TITLE
【PC/CONTACTページ】

### ISSUE THREAD

**Issue by umatobishima** [NKeisuke/ampersands-new-site#22]
@tetsuya0987 
- [x] 1.OUR OFFICEを文章の上に合わせてください。
- [x] 2.游ゴシック　ボールドにしてください。
  そして行間も少し広げてください。（inVisionを参照してください）
- [x] 3.文字を太くしつつ、字間を少しあけてください。
- [x] 4.スペースを半分にしてください。
- [x] 5.スペースを半分にしてください。
- [x] 6.三角形が白いのでネイビーにしてください。
  FEATUREの文字を上に揃えてください。

![14](https://cloud.githubusercontent.com/assets/17138127/17284833/1bbb9974-57f9-11e6-997d-08c701619dca.jpg)

**Comment by NKeisuke** [comment]
クローズします！ありがとうございます！
