### ISSUE TITLE
【PC】CONTACTページ

### ISSUE THREAD

**Issue by umatobishima** [NKeisuke/ampersands-new-site#27]
@tetsuya0987 
- [ ] 1. 航空写真や、ズームのメニュー取れますか？

![k](https://cloud.githubusercontent.com/assets/17138127/17724681/0e0a8c6c-647f-11e6-8ec2-6c0aff873489.jpg)

**Comment by NKeisuke** [comment]
@tetsuya0987 もし取れない場合、表記を変更することは可能でしょうか？（参照→ http://jp.ouwn.jp/about）

**Comment by NKeisuke** [comment]
@tetsuya0987 

35.7001772,139.7453084

**Comment by NKeisuke** [comment]
@tetsuya0987 

35.7001871,139.7459016

**Comment by NKeisuke** [comment]
@tetsuya0987 

35.7000794,139.745904

**Comment by NKeisuke** [comment]
@tetsuya0987 

35.7001138,139.7460154

**Comment by NKeisuke** [comment]
@tetsuya0987 

35.7000915,139.7462314
