### ISSUE TITLE
【PC／SP共通 PROJECT 記事ページ】

### ISSUE THREAD

**Issue by NKeisuke** [NKeisuke/ampersands-new-site#31]
- [x] 記事本文中に入れたURLをリンクにすることは出来ますか？

![2016-08-17 13 57 29](https://cloud.githubusercontent.com/assets/17138141/17725097/ec4140ea-6482-11e6-86b8-ca570e7b3260.png)

**Comment by tetsuya0987** [comment]
<a href="リンク先">文章</a>

↑こんな感じで<a>タグを囲んでやればリンクにできます。

**Comment by NKeisuke** [comment]
@tetsuya0987 カスタムフィールドテンプレートだからか、ちょっとうまく出来なかったので、
この記事の文中URLで一度書き方を教えて下さいー。
http://test.ampsds.jp/wp-admin/post.php?post=192&action=edit
