### ISSUE TITLE
【SP/NEWSページ/サムネイル】デザイン・表示修正

### ISSUE THREAD

**Issue by NKeisuke** [NKeisuke/ampersands-new-site#5]
- [x] 1. NEWSの位置を10pxほど上に上げて下さい
- [x] 2. NEWSの文字サイズを90%ほど縮小して、書体を太くして下さい。
- [x] 3. 画像の縦幅をInvisionに合わせて下さい。
- [x] 4. 日付のサイズを85%ほど縮小して下さい
- [x] 5. 日付と欧文を現状から15pxほど空けて下さい
- [x] 6. 欧文タイトルの字間を若干空けて下さい
- [x] 7. 見出しを75%ほど縮小して、書体を太くして下さい
- [x] 8. 本文の行間を少し（6px分ほど）空けて下さい
- [x] 9. 本文を3Lで切り、READ MOREホタンを付けて下さい。（現状全て表示されてしまっています）
- [x] 10. READ MOREボタンの書体、現状より太くして下さい。

![003](https://cloud.githubusercontent.com/assets/17138141/17269237/1ce9a89e-567e-11e6-8f79-9516fff3d489.jpg)

**Comment by umatobishima** [comment]
@NKeisuke 

> 1. 画像の縦幅をInvisionに合わせて下さい。

これがPCと同じ比率じゃないとだめかも。
