### ISSUE TITLE
【SP　フッター色変え】

### ISSUE THREAD

**Issue by umatobishima** [NKeisuke/ampersands-new-site#51]
@tetsuya0987 

フッターの部分に白地を入れることはできますか？
なおかつ文字の色を濃いネイビーにしてください。

前後のスペースを他と同じく100PXにしてください。

![c](https://cloud.githubusercontent.com/assets/17138127/18040152/5d47f408-6de5-11e6-9813-e25ed870e903.jpg)

**Comment by tetsuya0987** [comment]
ネイビーカラーの「ampersands」の画像用意してください。
