### ISSUE TITLE
【PC／ボタンのアクション】

### ISSUE THREAD

**Issue by NKeisuke** [NKeisuke/ampersands-new-site#53]
- [x] 1.トップページの動画下のボタン、マウスオーバー時にボタンの色が＜**薄い青 → 白**＞にフォードがかって変わるようにして下さい。
  　
  　
  　
  ![001](https://cloud.githubusercontent.com/assets/17138141/18041764/0ddcdab6-6df7-11e6-82a5-5158949ea836.jpg)

　
　

　
- [x] 2.トップとニュースにつく「MORE」ボタン、マウスオーバー時にボタンの色が＜**薄い青 → 濃い青**＞にフェードがかって変わるようにして下さい。

　
　
　
![002](https://cloud.githubusercontent.com/assets/17138141/18041887/df3571e0-6df7-11e6-972d-9737929b08b6.jpg)
![003](https://cloud.githubusercontent.com/assets/17138141/18041888/df3766d0-6df7-11e6-963d-2b875d9c0e32.jpg)

**Comment by NKeisuke** [comment]
@tetsuya0987 こちらも画像のマウスオーバー同様、もう若干フェードの動きが早くていいかと思いますー。

**Comment by tetsuya0987** [comment]
早めに設定しました。
