### ISSUE TITLE
【SP/NEWSページ/記事本文】デザイン・表示修正

### ISSUE THREAD

**Issue by NKeisuke** [NKeisuke/ampersands-new-site#6]
記事冒頭部分の修正はこちらのissueに準じて下さい。
↓
https://github.com/NKeisuke/ampersands-new-site/issues/5
- [x] 1. 前後の記事の文字サイズを70%縮小し、若干行間をつめて、下線を外して下さい。
- [x] 2. サムネイルボタンを115%拡大して下さい。
- [x] 3. スペースを50pxほど縮めて下さい（下の幅も同等に）
- [x] 4. 前後の記事とサムネイルボタンをセンターに揃えて下さい（Invision参照）
- [x] 5. FEATUREの書体を太くして、字間を若干詰めて下さい。
- [x] 6. 境目がズレていますが、バグでしょうか？？
- [x] 7. FEATUREの画像の縦幅、Invisionに合わせて（50pxほど）狭めて下さい
- [x] 8. カテゴリー名「GRAPHIC DESIGN」の字間ほんの少し詰めて下さい
- [x] 9. 矢印のアイコンの色、反転して下さい。（データ必要でしょうか？）
- [x] 10. 次の記事の画像までの間隔、20pxほど空けて下さい。

![005](https://cloud.githubusercontent.com/assets/17138141/17269675/faf7e5be-5689-11e6-87f5-4cbfab506b00.jpg)

**Comment by umatobishima** [comment]
@NKeisuke 

> 1. FEATUREの画像の縦幅、Invisionに合わせて（50pxほど）狭めて下さい

ここもPCと同じ比率じゃないとだめかも。
