### ISSUE TITLE
【SP/ABOUTページ】デザイン修正、テキスト差し替え

### ISSUE THREAD

**Issue by NKeisuke** [NKeisuke/ampersands-new-site#7]
- [x] このページのテキスト下記のデータのものに全て差し替えて下さい。
  http://ampsds.jp/data/new_web_smartphone_0730.zip
- [x] 1. ABOUT USの文字を140%ほど拡大して下さい
- [x] 2. 10pxほどスペースを詰めて下さい
- [x] 3. DESIGNのカテゴリを「PHILOSOPHY」に変更して下さい
- [x] 4. 各カテゴリ（DESIGN〜）の文字サイズを130%ほど拡大して下さい
- [x] 5. 各カテゴリと下の画像のスペースを20pxほど詰めて下さい
- [x] 6. PHILOSOPHYの文字サイズを140%拡大して下さい
- [x] 7. PHILOSOPHYにつく本文の行間少し（6pxほど）空けて、書体を太くして下さい
- [x]  ※ PHILOSOPHY、PRINT、AMPLOG、MEMBERのカテゴリは下にスクロールしても表示させて下さい。

※ 以下PRINT, AMPLOGの部分も同じ修正をお願いします。

![006](https://cloud.githubusercontent.com/assets/17138141/17270339/6287c15c-569b-11e6-9af4-4d98f85f9aa1.jpg)

**Comment by NKeisuke** [comment]
1. PHILOSOPHYにつく本文の行間少し（6pxほど）空けて、書体を太くして下さい

こちら書体が細いままかと思いますので、太くして下さいー！
（すみません、漏れてましたが、PRINTとAMPLOGの下につく本文も太くして下さい）

**Comment by umatobishima** [comment]
@tetsuya0987 
すみません！
1. 各カテゴリ（DESIGN〜）の文字サイズを130%ほど拡大して下さい

現状、iphone 5だとAMPLOGで改行されるので
MEMBERまで入るように調整してもらえると助かります！

**Comment by umatobishima** [comment]
@tetsuya0987 
スクロールすると、ローカルナビの上が空いたままなので
上のスペースを詰めてください。

![img_2240](https://cloud.githubusercontent.com/assets/17138127/17697250/aff2fde8-63ee-11e6-84b9-51221b884df6.PNG)
